import {chromium} from '../web-tools/node_modules/playwright/index.mjs';import fs from 'node:fs';import crypto from 'node:crypto';
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});const errors=[],resources=[],pending=[];
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());if(/\/(viewer.js|viewer.css|house.glb)$/.test(r.url()))pending.push((async()=>{const body=await r.body();resources.push({url:r.url(),status:r.status(),bytes:body.length,sha256:crypto.createHash('sha256').update(body).digest('hex')});})());});
const start=Date.now();const response=await page.goto('https://gatdeguin.github.io/42/',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__viewer?.ready,{timeout:60000});await page.waitForTimeout(700);
const report={url:page.url(),status:response.status(),loadMs:Date.now()-start,views:[],desktop:await page.evaluate(()=>({stats:__viewer.stats,width:innerWidth,scroll:document.documentElement.scrollWidth})),metadata:await page.evaluate(()=>fetch('./assets/model-info.json').then(r=>r.json()))};
for(const key of ['exterior','pb','pa','estudio','quincho','cocina','dormitorio','vestidor','bano','pileta','huerta','mono','acceso']){await page.click('[data-view="'+key+'"]');await page.waitForTimeout(1400);await page.screenshot({path:'D:/2026/42/audit/integral95_public_'+key+'.png'});report.views.push(await page.evaluate(()=>({label:document.getElementById('view-name').textContent,camera:__viewer.camera.position.toArray(),stats:__viewer.stats})));}
const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});mobile.on('pageerror',e=>errors.push('mobile '+e.message));await mobile.goto('https://gatdeguin.github.io/42/',{waitUntil:'networkidle'});await mobile.waitForFunction(()=>window.__viewer?.ready,{timeout:60000});await mobile.waitForTimeout(700);await mobile.screenshot({path:'D:/2026/42/audit/integral95_public_mobile.png'});
await mobile.click('#menu');await mobile.waitForTimeout(300);await mobile.click('[data-view="estudio"]');await mobile.waitForTimeout(1400);await mobile.screenshot({path:'D:/2026/42/audit/integral95_public_mobile_studio.png'});
report.mobile=await mobile.evaluate(()=>({stats:__viewer.stats,width:innerWidth,scroll:document.documentElement.scrollWidth}));
await Promise.all(pending);report.resources=resources;report.errors=errors;fs.writeFileSync('D:/2026/42/audit/integral95_public_checks.json',JSON.stringify(report,null,2));console.log(JSON.stringify({url:report.url,status:report.status,loadMs:report.loadMs,views:report.views.length,resources,errors}));await browser.close();
