"""Publish stills plus a responsive gallery; preserve the source SHA and current review status."""
from pathlib import Path
from PIL import Image
import json,hashlib,html
ROOT=Path(__file__).resolve().parents[1];src=ROOT/'review95/r6k_stills';out=ROOT/'docs/renders';out.mkdir(parents=True,exist_ok=True)
r=json.loads((src/'manifest.json').read_text(encoding='utf8'));assert len(r['images'])==19
for item in r['images']:
 p=src/item['file'];dst=out/(p.stem+'.jpg')
 Image.open(p).convert('RGB').save(dst,quality=94,optimize=True,subsampling=0)
 item.update({'source_png_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'file':dst.name,'sha256':hashlib.sha256(dst.read_bytes()).hexdigest(),'bytes':dst.stat().st_size})
(out/'manifest.json').write_text(json.dumps(r,ensure_ascii=False,indent=2),encoding='utf8')
cards=''.join('<figure><a href="'+x['file']+'"><img src="'+x['file']+'" alt="'+html.escape(x['title'])+'" loading="lazy" width="'+str(x['pixels'][0])+'" height="'+str(x['pixels'][1])+'"></a><figcaption><span>'+html.escape(x['title'])+'</span><a href="'+x['file']+'" download>Descargar JPG</a></figcaption></figure>' for x in r['images'])
doc='''<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Casa de campo · Fotografías del modelo</title>
<style>
:root{color-scheme:dark;font-family:system-ui,sans-serif;color:#f1efe8;background:#181a17}*{box-sizing:border-box}body{margin:0}header,main,footer{max-width:1500px;margin:auto;padding:28px clamp(18px,4vw,60px)}nav{display:flex;gap:24px;flex-wrap:wrap;margin-bottom:44px}a{color:inherit;text-underline-offset:5px}h1{font-family:Georgia,serif;font-size:clamp(36px,5vw,68px);font-weight:400;letter-spacing:-.04em;margin:18px 0}.eyebrow{text-transform:uppercase;letter-spacing:.14em;font-size:12px;color:#c8b990}p{max-width:850px;line-height:1.6;color:#c6cac2}.status{display:inline-block;border:1px solid #79724f;border-radius:24px;padding:8px 15px;font-size:13px;color:#dfcfa2}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:38px 24px}figure{margin:0;min-width:0}figure:first-child{grid-column:1/-1}figure img{display:block;width:100%;height:auto;background:#242720}figure a:focus-visible{outline:3px solid #dfcfa2;outline-offset:5px}figcaption{display:flex;justify-content:space-between;align-items:baseline;gap:12px;padding-top:14px;font-size:15px}figcaption a{font-size:12px;color:#b8c0b2}footer{border-top:1px solid #383d34;font-size:12px;color:#b8c0b2;overflow-wrap:anywhere}dialog{padding:0;border:0;background:#10110f;color:white;max-width:96vw;max-height:95vh}dialog::backdrop{background:#000d}dialog img{max-width:95vw;max-height:84vh;display:block;object-fit:contain}dialog button{padding:14px 22px;border:0;background:#2e332b;color:white;cursor:pointer;float:right}dialog p{margin:14px 20px}@media(max-width:700px){.grid{grid-template-columns:1fr;gap:28px}nav{gap:18px;margin-bottom:30px}header,main,footer{padding:22px 18px}figcaption{font-size:14px}}
</style><header><nav><a href="../">Volver al modelo 3D</a><a href="../planos/">Planos de la propiedad</a><a href="https://github.com/GatDeguin/42">Repositorio</a></nav><div class="eyebrow">Virrey del Pino · La Matanza · Buenos Aires</div><h1>La casa, ambiente por ambiente.</h1><div class="status">En revisión · aprobación global 9,5 pendiente</div><p>Imágenes calculadas desde el modelo arquitectónico R6K. Los encuadres muestran la distribución, los materiales y las correcciones de mobiliario. El video permanece pausado hasta la aprobación explícita del propietario.</p></header><main class="grid">'''+cards+'''</main><footer><p>19 imágenes Cycles · modelo '''+html.escape(r['source_model'])+'''<br>SHA256 '''+r['source_sha256']+'''</p><a href="manifest.json">Trazabilidad de las imágenes</a><p>Visualización arquitectónica en desarrollo. Los detalles propuestos y las verificaciones pendientes están identificados en los planos y la auditoría.</p></footer><dialog id="zoom"><button type="button" aria-label="Cerrar imagen">Cerrar ×</button><img alt=""><p></p></dialog><script>
const d=document.getElementById('zoom');document.querySelectorAll('figure>a').forEach(a=>a.addEventListener('click',e=>{if(e.ctrlKey||e.metaKey||e.shiftKey)return;e.preventDefault();const im=a.querySelector('img');d.querySelector('img').src=a.getAttribute('href');d.querySelector('img').alt=im.alt;d.querySelector('p').textContent=im.alt;d.showModal()}));d.querySelector('button').onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d)d.close()});
</script></html>'''
(out/'index.html').write_text(doc,encoding='utf8');print('GALLERY_READY',len(r['images']),r['source_sha256'])
