from pathlib import Path
import json,shutil,html
root=Path(r'D:\2026\42');src=root/'planos95/pass1c';dest=root/'docs/planos';dest.mkdir(exist_ok=True)
manifest=json.loads((src/'manifest.json').read_text(encoding='utf8'))
for p in src.iterdir():
 if p.suffix in ['.pdf','.zip','.svg','.dxf'] or p.name in ['manifest.json','measurements.json','verification.json','print_validation.json','README.md']:shutil.copy2(p,dest/p.name)
cards=[]
for s in manifest['sheets']:
 cards.append(f"""<article><a class="sheet" href="{s['svg']}" target="_blank"><img loading="lazy" src="{s['svg']}" alt="{html.escape(s['id']+' · '+s['title'])}"></a><div class="caption"><h2>{html.escape(s['id']+' · '+s['title'])}</h2><nav aria-label="Descargas {s['id']}"><a href="{s['svg']}" download>SVG ↓</a><a href="{s['dxf']}" download>DXF ↓</a></nav></div></article>""")
page="""<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#183638"><link rel="icon" href="data:,"><title>Planos · Casa de Campo / 42</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f3ef;color:#213b3d;font-family:Arial,sans-serif}header{background:#183638;color:white;padding:22px max(24px,calc((100vw - 1320px)/2));display:flex;justify-content:space-between;gap:18px;align-items:center}header a{color:#fff;text-decoration:none}header strong{letter-spacing:.1em;font-size:14px}main{max-width:1320px;margin:auto;padding:54px 24px}.intro{max-width:800px}.eyebrow{font-size:11px;letter-spacing:.15em;text-transform:uppercase;color:#55716c}h1{font-size:clamp(32px,4vw,52px);font-weight:500;letter-spacing:-.045em;margin:12px 0 18px}p{line-height:1.65;color:#536761;font-size:15px}.downloads{display:flex;gap:12px;flex-wrap:wrap;margin:25px 0}.button{display:inline-block;border:1px solid #183638;padding:14px 20px;border-radius:5px;text-decoration:none;color:#183638;font-size:14px;font-weight:600}.primary{background:#183638;color:#fff}.note{padding:18px 20px;border-left:3px solid #ac783e;background:#eeeadf;font-size:13px;margin:30px 0;line-height:1.6}.note strong{color:#70502c}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}article{border:1px solid #d7ddd4;background:white;border-radius:5px;overflow:hidden}.sheet{display:block;background:#fff}.sheet img{display:block;width:100%;aspect-ratio:594/420;object-fit:contain}.caption{padding:18px;border-top:1px solid #e8eae5;display:flex;gap:14px;justify-content:space-between;align-items:center}h2{font-size:14px;font-weight:600;margin:0}.caption nav{display:flex;gap:15px;white-space:nowrap}.caption a{font-size:12px;color:#476761;text-decoration:none}.caption a:hover{text-decoration:underline}footer{margin-top:35px;font-size:12px;line-height:1.8;color:#647972}footer a{color:inherit}a:focus-visible{outline:3px solid #bf8538;outline-offset:4px}@media(max-width:690px){main{padding:32px 16px}.grid{grid-template-columns:1fr}.caption{align-items:flex-start;flex-direction:column}header{padding:20px 16px;font-size:13px}.downloads{flex-direction:column}.button{text-align:center}}
</style></head><body><header><strong>42 / CASA DE CAMPO</strong><a href="../">Volver al modelo 3D ↗</a></header><main><div class="intro"><span class="eyebrow">Virrey del Pino · Buenos Aires · Cedro Misionero</span><h1>La propiedad, en planos.</h1><p>19 láminas A2 con implantación, plantas, fachadas, cortes y detalles. Incluyen el estudio de 3,20 m libres, la vivienda de 2,60 m, los accesos, la pileta y los esquemas de estructura e instalaciones.</p><div class="downloads"><a class="button primary" href="Casa_de_Campo_Planos_A2.pdf" target="_blank">Abrir planos en PDF ↗</a><a class="button" href="Casa_de_Campo_Planos_Editables.zip" download>Descargar PDF + SVG + DXF ↓</a></div></div><div class="note"><strong>Entrega en revisión · modelo Pass1c.</strong> Estas láminas documentan las correcciones de escalera, umbrales y pluviales. El visor principal conserva la versión publicada anterior mientras se verifica su actualización. La última auditoría integral obtuvo 6,9/10; el umbral de aprobación es 9,5. Las propuestas y verificaciones pendientes se identifican en cada lámina. No es un proyecto ejecutivo aprobado para construcción.</div><div class="grid">CARDS</div><footer>PDF y SVG: imprimir en A2 (594 × 420 mm), al 100 % y sin ajustar a página. DXF: unidades en metros.<br>Norte orientativo según el propietario; acometidas de servicios por confirmar. <a href="manifest.json">Versión y trazabilidad</a> · <a href="print_validation.json">Validación documental</a></footer></main></body></html>"""
(dest/'index.html').write_text(page.replace('CARDS',''.join(cards)),encoding='utf8')
p=root/'docs/index.html';s=p.read_text(encoding='utf8');s=s.replace('<span class="live">Modelo interactivo</span>','<a href="./planos/">Planos ↗</a><span class="live">Modelo interactivo</span>')
s=s.replace('Geometría del modelo final auditado. Los materiales e iluminación están adaptados a la visualización en tiempo real.','Versión publicada en revisión. La auditoría exige 9,5 y realismo fotográfico. Consulta las correcciones constructivas en el juego de planos.')
p.write_text(s,encoding='utf8')
print('Published local drawings page and19sheets')
