import {chromium} from 'playwright';import fs from 'node:fs';import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});const variant=process.env.PHOTO95_GI||'raw';const report={variant,created:new Date().toISOString(),runs:[],errors:[]};
try{for(const gi of [false,true]){
 const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});page.on('pageerror',e=>{report.errors.push(e.message);console.log('ERROR',e.message)});page.on('response',r=>{if(r.status()>=400)report.errors.push(r.status()+' '+r.url())});
 const start=Date.now();await page.goto('http://127.0.0.1:8420/preview95/?mode=raster'+(gi?'&gi='+(process.env.PHOTO95_GI||'1')+(process.env.PHOTO95_ALLOW_STALE==='1'?'&allowStaleGI=1':''):''));await page.waitForFunction(()=>window.__viewer?.ready,null,{timeout:120000});const readyMs=Date.now()-start;await page.evaluate(()=>__viewer.selectView('estudio',true));await page.waitForTimeout(1600);
 await page.screenshot({path:'docs/preview95/screenshots/gi-'+(gi?(process.env.PHOTO95_GI||'baked'):'baseline')+'-studio.jpg',quality:85});await page.screenshot({path:'docs/preview95/screenshots/gi-'+(gi?'baked':'baseline')+'-studio.png'});
 const row=await page.evaluate(()=>({stats:__viewer.stats,metrics:__viewer.photo.metrics,camera:__viewer.camera.position.toArray(),target:__viewer.controls.target.toArray()}));row.readyMs=readyMs;row.gi=gi;report.runs.push(row);console.log('RUN',gi,readyMs,row.metrics.bake);
 if(gi){assert(row.metrics.bake.surfaces>5);assert.equal(row.metrics.bake.appliedSurfaces,row.metrics.bake.surfaces,'Not all baked surfaces are displayed');assert.deepEqual(row.metrics.bake.unmatchedSurfaces,[]);await page.evaluate(()=>__viewer.setAllDoors(1));await page.waitForFunction(()=>Array.from(__viewer.doors.values()).every(d=>d.node.position.distanceTo(d.openP)<.002&&d.node.quaternion.angleTo(d.openQ)<.002),null,{timeout:30000});report.doors=await page.evaluate(()=>__viewer.stats.doors);await page.check('#cut-enabled');await page.locator('#cut').fill('4.5');await page.locator('#cut').dispatchEvent('input');await page.waitForTimeout(100);report.cut=await page.evaluate(()=>__viewer.renderer.clippingPlanes[0].constant);}
 await page.close();
}assert.deepEqual(report.errors,[]);fs.writeFileSync('docs/preview95/gi/qa-'+variant+'.json',JSON.stringify(report,null,2));console.log('GI_QA_COMPLETE',report.errors);
}catch(error){report.failure=error.stack;fs.writeFileSync('docs/preview95/gi/qa-'+variant+'.json',JSON.stringify(report,null,2));throw error;}finally{await browser.close();}
