import fs from 'node:fs';
import path from 'node:path';
import {build} from './.cache/photographic95/node_modules/esbuild/lib/main.js';
const root=path.resolve(import.meta.dirname,'..'), out=path.join(root,'docs/preview95');
const dependency=path.join(import.meta.dirname,'.cache/photographic95/node_modules');
const cp=(a,b)=>{fs.mkdirSync(path.dirname(b),{recursive:true});fs.copyFileSync(a,b);};
for(const file of fs.readdirSync(path.join(root,'source/textures')))cp(path.join(root,'source/textures',file),path.join(out,'assets/textures',file));
cp(path.join(root,'source/belfast_sunset_2k.hdr'),path.join(out,'assets/belfast_sunset_2k.hdr'));
const source=JSON.parse(fs.readFileSync(path.join(root,'source/scene.json'),'utf8'));
fs.writeFileSync(path.join(out,'assets/material-profiles.json'),JSON.stringify({profiles:source.profiles,materials:source.materials}));
fs.writeFileSync(path.join(out,'vendor/entry.js'),`export {WebGLPathTracer,DenoiseMaterial} from 'three-gpu-pathtracer';
export {FullScreenQuad} from 'three/examples/jsm/postprocessing/Pass.js';
export {GenerateMeshBVHWorker} from 'three-mesh-bvh/src/workers/GenerateMeshBVHWorker.js';
export {RGBELoader} from 'three/examples/jsm/loaders/RGBELoader.js';
export {RectAreaLightUniformsLib} from 'three/examples/jsm/lights/RectAreaLightUniformsLib.js';
export {EffectComposer} from 'three/examples/jsm/postprocessing/EffectComposer.js';
export {RenderPass} from 'three/examples/jsm/postprocessing/RenderPass.js';
export {GTAOPass} from 'three/examples/jsm/postprocessing/GTAOPass.js';
export {OutputPass} from 'three/examples/jsm/postprocessing/OutputPass.js';`);
await build({entryPoints:[path.join(out,'vendor/entry.js')],outfile:path.join(out,'vendor/photographic-runtime.js'),bundle:true,format:'esm',minify:true,plugins:[{name:'one-three-runtime',setup(b){b.onResolve({filter:/^three$/},()=>({path:'three',external:true}));}}],nodePaths:[dependency]});
await build({entryPoints:[path.join(dependency,'three-mesh-bvh/src/workers/generateMeshBVH.worker.js')],outfile:path.join(out,'vendor/generateMeshBVH.worker.js'),bundle:true,format:'esm',minify:true,nodePaths:[dependency]});
for(const [pkg,name] of [['three-gpu-pathtracer','PATH-TRACER-LICENSE.txt'],['three-mesh-bvh','BVH-LICENSE.txt'],['three','THREE-LICENSE.txt']])cp(path.join(dependency,pkg,'LICENSE'),path.join(out,'vendor',name));
fs.writeFileSync(path.join(out,'vendor/versions.json'),JSON.stringify({three:'0.180.0','three-gpu-pathtracer':'0.0.24','three-mesh-bvh':'0.9.5',esbuild:'0.25.10'},null,2));
const promoted=fs.readFileSync(path.join(root,'docs/index.html'),'utf8').includes('id="candidate-base"');
let html=fs.readFileSync(path.join(root,promoted?'docs/preview95/index.html':'docs/index.html'),'utf8');
if(!promoted)html=html.replaceAll('./vendor/','../vendor/').replace('href="./planos/"','href="../planos/"');
html=html.replace('https://github.com/GatDeguin/42/blob/main/output/Casa_de_Campo_Final.blend','./README.md').replace('Abrir proyecto Blender ↗','Fuente de esta candidata ↗');
if(!html.includes('id="photo-mode"'))html=html.replace('Modelo interactivo','Prueba de iluminación').replace('<section><h2>Inspeccionar</h2>',`<section><h2>Calidad de luz</h2><label class="switch-row"><span>Luz progresiva al detenerse</span><input id="photo-mode" type="checkbox" role="switch"></label><label class="switch-row"><span>Sombras de contacto</span><input id="contact-mode" type="checkbox" checked role="switch"></label><p class="micro" id="photo-status" aria-live="polite">Preparando iluminación…</p></section><section><h2>Inspeccionar</h2>`);
fs.writeFileSync(path.join(out,'index.html'),html);
cp(path.join(root,'docs/viewer.css'),path.join(out,'viewer.css'));
let js=fs.readFileSync(path.join(root,'docs/viewer.js'),'utf8').replaceAll("'./assets/","'../assets/");
js=js.replace("import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';","import {createPhotographicPipeline} from './photographic.js';");
js=js.replace('let renderer, scene, camera, controls,','let photo, renderer, scene, camera, controls,');
js=js.replace("const webTextures={}","const assetRoot=new URLSearchParams(location.search).has('previous')?'../assets/':'./assets/';\nconst webTextures={}");
js=js.replace("fetch('../assets/model-info.json')","fetch(assetRoot+'model-info.json')");
js=js.replace("fetch('../assets/textures/wood-surfaces.json')","fetch(assetRoot+'textures/wood-surfaces.json')");
js=js.replace("loader.loadAsync('../assets/house.glb',","loader.loadAsync(assetRoot+'house.glb',");
js=js.replace('function setVisibility(){','function setVisibility(){\n photo?.invalidate(true);');
js=js.replace('function setCut(){','function setCut(){\n photo?.invalidate(false);');
js=js.replace('const d=doors.get(key);if(!d)return;d.target=value;','const d=doors.get(key);if(!d)return;d.target=value;photo?.invalidate(true);');
js=js.replace("function clearSelection(){selected=null;","function clearSelection(){photo?.invalidate(false);selected=null;");
js=js.replace("clearSelection();selected=o;","clearSelection();selected=o;photo?.invalidate(false);");
js=js.replace('o.castShadow=!materials.some(m=>m.transparent)', 'photo.prepareMesh(o);\n  o.castShadow=!materials.some(m=>m.transparent)');
js=js.replace('renderer.toneMapping=THREE.ACESFilmicToneMapping','renderer.toneMapping=THREE.AgXToneMapping');
js=js.replace("scene.background=new THREE.Color(0xe8ede8);scene.fog=new THREE.Fog(0xe8ede8,65,150);","scene.background=new THREE.Color(0xe8ede8);");
const envStart=js.indexOf('  const pmrem=');
const envEnd=js.indexOf('  const ground=',envStart);
js=js.slice(0,envStart)+"  photo=await createPhotographicPipeline({THREE,renderer,scene,camera,controls,viewport,mobile,status:$('photo-status')});\n"+js.slice(envEnd);
js=js.replace('roughness:1}));ground.rotation','roughness:1,map:photo.textures.outerGrass.albedo,normalMap:photo.textures.outerGrass.normal,normalScale:new THREE.Vector2(.25,.25)}));ground.rotation');
js=js.replace('new THREE.PlaneGeometry(300,300)','photo.groundGeometry()');
js=js.replace('camera=new THREE.PerspectiveCamera(46,1,.035,400)','camera=new THREE.PerspectiveCamera(46,1,.035,5000)');
js=js.replace('ground.position.set(11,-.20,10)','ground.position.set(0,-.20,0)');
js=js.replace('color:0x8f9b79','color:0xffffff');
js=js.replace('ground.rotation.x=-Math.PI/2;', 'ground.material.map=ground.material.map.clone();ground.material.map.repeat.set(.25,.25);ground.material.normalMap=ground.material.normalMap.clone();ground.material.normalMap.repeat.set(.25,.25);ground.rotation.x=-Math.PI/2;');
js=js.replace('renderer.setSize(w,h,false);','renderer.setSize(w,h,false);photo?.resize(w,h);');
js=js.replace("setupBatching(model);ready=true;", "setupBatching(model);await photo.warmup();photo.completeSetup();ready=true;");
// Preserve shared photo-tree geometry. The path tracer requires individual Mesh transforms.
js=js.replace('const dynamic=!!doorAncestor(o);',"const sharedAsset=(data.label||'').startsWith('BOT95 |');o.userData.sharedAsset=sharedAsset;const dynamic=!!doorAncestor(o);");
js=js.replace('if(dynamic||Array.isArray(o.material))', 'if(dynamic||sharedAsset||Array.isArray(o.material))');
js=js.replace('if(o.userData.dynamic)o.visible=', 'if(o.userData.dynamic||o.userData.sharedAsset)o.visible=');
js=js.replace("o.castShadow=!materials.some(m=>m.transparent)&&data.category!=='LANDSCAPE';","o.castShadow=sharedAsset||(!materials.some(m=>m.transparent)&&data.category!=='LANDSCAPE');");
js=js.replace("const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);","const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);if(metadata.gi?.enabled&&new URLSearchParams(location.search).has('gi'))await photo.loadBake(loader);");
js=js.replace('downloadBytes:metadata.stats.downloadBytes','sourceModel:metadata.stats.source_model,sourceSHA:metadata.stats.source_sha256,downloadBytes:metadata.stats.downloadBytes');
js=js.replace('selectView,setAllDoors,get camera()', 'selectView,setAllDoors,get photo(){return photo;},get scene(){return scene;},get controls(){return controls;},get camera()');
js=js.replace('controls.update();renderer.render(scene,camera);',"controls.update();photo.render(now,{moving:!!cameraMove||Array.from(doors.values()).some(d=>Math.abs(d.value-d.target)>.0001),cut:$('cut-enabled').checked,selected:!!selected});");
js=js.replace('start();',"$('photo-mode').addEventListener('change',e=>photo.setEnabled(e.target.checked));\n$('contact-mode').addEventListener('change',e=>photo.setContact(e.target.checked));\nstart();");
fs.writeFileSync(path.join(out,'viewer.js'),js);
console.log('Prepared isolated runtime, HDR, 63 source maps, and copied viewer');


const {preparePromotion}=await import('./photographic95-promotion.mjs');preparePromotion(out);
