import fs from 'node:fs';
const file='docs/preview95/photographic.js';let s=fs.readFileSync(file,'utf8');
s=s.replace('WebGLPathTracer,GenerateMeshBVHWorker,','WebGLPathTracer,DenoiseMaterial,FullScreenQuad,GenerateMeshBVHWorker,');
s=s.replace("const m=new THREE.MeshPhysicalMaterial();THREE.MeshStandardMaterial.prototype.copy.call(m,old);m.defines={STANDARD:'',PHYSICAL:''};",`const key=old.name.split('|').at(-1).trim();
  const physical=['glass','glassInner','water','fabric','clothWhite','acoustic'].includes(key);
  const m=physical?new THREE.MeshPhysicalMaterial():old.clone();
  if(physical){THREE.MeshStandardMaterial.prototype.copy.call(m,old);m.defines={STANDARD:'',PHYSICAL:''};}`);
s=s.replace("  const key=old.name.split('|').at(-1).trim();\n  const definition",'  const definition');
s=s.replace('m.sheen=.35;','m.sheen=.35;');
s=s.replace('m.thickness=key',"m.thickness=key");
s=s.replace('const raster=()=>composer.render();',"const raster=()=>composer.render();\n const denoise=new DenoiseMaterial({sigma:2,threshold:.065,kSigma:1});const denoiseQuad=new FullScreenQuad(denoise);");
s=s.replace('pathTracer.minSamples=4;','pathTracer.minSamples=32;');
s=s.replace('pathTracer.dynamicLowRes=false;',`pathTracer.dynamicLowRes=false;
    pathTracer.renderToCanvasCallback=(target,r,quad)=>{denoise.map=target.texture;denoise.opacity=quad.material.opacity;denoise.transparent=denoise.opacity<1;denoise.blending=denoise.transparent?THREE.NormalBlending:THREE.NoBlending;const prior=r.autoClear;r.autoClear=false;denoiseQuad.render(r);r.autoClear=prior;};`);
s=s.replace('triangles:pathTracer._generator.geometry.attributes.position.count/3','triangles:(pathTracer._generator.geometry.index?.count||pathTracer._generator.geometry.attributes.position.count)/3');
s=s.replace("get metrics(){return {...metrics,enabled", "get metrics(){return {...metrics,compiling:pathTracer?.isCompiling||false,enabled");
s=s.replace("  completeSetup(){complete=true;", "  async warmup(){const begin=performance.now();await renderer.compileAsync(scene,camera);metrics.rasterCompileMs=performance.now()-begin;},\n  completeSetup(){complete=true;");
s=s.replace("setEnabled(preference==='path'||(preference!=='raster'&&!mobile));","setEnabled(preference==='path');");
s=s.replace('  render(now,{moving,cut,selected}){','  render(now,{moving,cut,selected}){\n   renderer.info.reset();renderer.info.autoReset=false;');
s=s.replace("else if(building)status.textContent=", "else if(building||pathTracer?.isCompiling)status.textContent=");
fs.writeFileSync(file,s);
const build='web-tools/photographic95-build.mjs';s=fs.readFileSync(build,'utf8');
s=s.replace("export {WebGLPathTracer} from 'three-gpu-pathtracer';","export {WebGLPathTracer,DenoiseMaterial} from 'three-gpu-pathtracer';\nexport {FullScreenQuad} from 'three/examples/jsm/postprocessing/Pass.js';");
s=s.replace("setupBatching(model);photo.completeSetup();ready=true;", "setupBatching(model);await photo.warmup();photo.completeSetup();ready=true;");
s=s.replace("js=js.replace('renderer.setSize(w,h,false);'",`js=js.replace('new THREE.PlaneGeometry(300,300)','new THREE.PlaneGeometry(3000,3000)');
js=js.replace('camera=new THREE.PerspectiveCamera(46,1,.035,400)','camera=new THREE.PerspectiveCamera(46,1,.035,5000)');
js=js.replace('color:0x8f9b79','color:0xffffff');
js=js.replace('ground.rotation.x=-Math.PI/2;', 'ground.material.map=ground.material.map.clone();ground.material.map.repeat.set(750,750);ground.rotation.x=-Math.PI/2;');
js=js.replace('renderer.setSize(w,h,false);'`);
fs.writeFileSync(build,s);
