import {chromium} from 'playwright';import fs from 'node:fs';import assert from 'node:assert/strict';
const url=process.env.VIEWER_URL||'http://127.0.0.1:8420/';
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
const p=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});
await p.goto(url);await p.waitForFunction(()=>window.__viewer?.ready);
await p.click('[data-view="pb"]');await p.locator('#cut').fill('4.5');await p.locator('#cut').dispatchEvent('input');
const cut=await p.evaluate(()=>({label:document.querySelector('#view-name').textContent,plane:__viewer.renderer.clippingPlanes[0].constant}));assert.equal(cut.label,'Planta baja · corte a 4,50 m');assert.equal(cut.plane,4.5);
await p.uncheck('#cut-enabled');assert.equal(await p.locator('#view-name').textContent(),'Planta baja');
await p.click('[data-view="vestidor"]');await p.waitForTimeout(1500);
const vestidor=await p.evaluate(()=>({allClosed:Array.from(__viewer.doors.values()).every(d=>d.target===0),camera:__viewer.camera.position.toArray()}));assert(vestidor.allClosed);assert(vestidor.camera[2]<9);
const wood=await p.evaluate(()=>__viewer.originals.filter(o=>o.material.name.includes('madera original')).map(o=>({label:o.userData.label,map:!!o.material.map,uv:!!o.geometry.attributes.uv})));assert(wood.length>180);assert(wood.every(o=>o.map&&o.uv));
await p.setViewportSize({width:390,height:844});await p.click('#home');await p.waitForTimeout(1300);
const portrait=await p.evaluate(()=>({camera:__viewer.camera.position.toArray(),width:innerWidth,scroll:document.body.scrollWidth}));assert.equal(portrait.width,portrait.scroll);
await p.setViewportSize({width:844,height:390});await p.waitForTimeout(400);
const landscape=await p.evaluate(()=>({camera:__viewer.camera.position.toArray(),width:innerWidth,scroll:document.body.scrollWidth}));assert.equal(landscape.width,landscape.scroll);assert.notDeepEqual(portrait.camera,landscape.camera);
await p.screenshot({path:'review/web_mobile_landscape.png'});
await p.setViewportSize({width:390,height:844});await p.waitForTimeout(400);await p.screenshot({path:'review/web_mobile_home.png'});
assert.deepEqual(errors,[]);
const report={url,errors,cut,cutDisabledLabel:'Planta baja',vestidor,woodMeshes:wood.length,allWoodMapped:true,portrait,landscape};fs.writeFileSync('review/web_revision_checks.json',JSON.stringify(report,null,2));console.log(report);await browser.close();
